// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5OxQWe7ZLkm44soscjlWUikAPJDcctg',
    appId: '1:980835869902:web:80ab6dcac8c59acd441c9f',
    messagingSenderId: '980835869902',
    projectId: 'ingo-abd97',
    authDomain: 'ingo-abd97.firebaseapp.com',
    storageBucket: 'ingo-abd97.firebasestorage.app',
    measurementId: 'G-5HNN6GR3RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Gmdrsj_zo0JZDwQJVJ2HHGuVw23WAJs',
    appId: '1:980835869902:android:22bdb745fe834169441c9f',
    messagingSenderId: '980835869902',
    projectId: 'ingo-abd97',
    storageBucket: 'ingo-abd97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYdEC2LY77c97TrAQ1xiN1C6ATf7lB7IQ',
    appId: '1:980835869902:ios:f31694d3c33ab21d441c9f',
    messagingSenderId: '980835869902',
    projectId: 'ingo-abd97',
    storageBucket: 'ingo-abd97.firebasestorage.app',
    iosBundleId: 'com.example.cardReaderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYdEC2LY77c97TrAQ1xiN1C6ATf7lB7IQ',
    appId: '1:980835869902:ios:f31694d3c33ab21d441c9f',
    messagingSenderId: '980835869902',
    projectId: 'ingo-abd97',
    storageBucket: 'ingo-abd97.firebasestorage.app',
    iosBundleId: 'com.example.cardReaderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs5OxQWe7ZLkm44soscjlWUikAPJDcctg',
    appId: '1:980835869902:web:672499c2623363e6441c9f',
    messagingSenderId: '980835869902',
    projectId: 'ingo-abd97',
    authDomain: 'ingo-abd97.firebaseapp.com',
    storageBucket: 'ingo-abd97.firebasestorage.app',
    measurementId: 'G-HY713YKT8Q',
  );
}
